In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.0-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.0-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.0-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 5.0 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.0 MB 5.6 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.0 MB 5.8 MB/s eta 0:00:02
   ----------------- ---------------------- 4.7/11.0 MB 5.9 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.0 MB 5.9 MB/s eta 0:00:01
   ------------------------- -------------- 7.1/11.0 MB 6.0 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/11.0 MB 6.0 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/11.0 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.8 MB/s eta 0:00:00
Downloading numpy-2.3.0-cp313-cp313-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.7 MB 6.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.7 MB 6.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.7 MB 6.1 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.7 MB 5.7 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.7 MB 5.7 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.7 MB 5.8 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.7 MB 5.9 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.7 MB 5.9 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.7 MB 5.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.7 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 5.7 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ---------------------------------------- 4/4 [pandas]

Successfully installed numpy-2.3.0 pandas-2.3.0 pytz-2025.2 tzdata-2025.2

In [3]:
import pandas as pd

In [4]:
!pip install kaggle

Collecting kaggle
  Downloading kaggle-1.7.4.5-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: bleach in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2025.4.26)
Requirement already satisfied: charset-normalizer in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (3.10)
Collecting protobuf (from kaggle)
  Downloading protobuf-6.31.1-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.9.0.post0)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: requests in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (1.17.0)
Collecting text-unidecode (from kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting tqdm (from kaggle)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: colorama in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-1.7.4.5-py3-none-any.whl (181 kB)
Downloading protobuf-6.31.1-cp310-abi3-win_amd64.whl (435 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: text-unidecode, tqdm, python-slugify, protobuf, kaggle

   -------- ------------------------------- 1/5 [tqdm]
   -------- ------------------------------- 1/5 [tqdm]
   -------- ------------------------------- 1/5 [tqdm]
   -------- ------------------------------- 1/5 [tqdm]
   ---------------- ----------------------- 2/5 [python-slugify]
   ------------------------ --------------- 3/5 [protobuf]
   ------------------------ --------------- 3/5 [protobuf]
   ------------------------ --------------- 3/5 [protobuf]
   ------------------------ --------------- 3/5 [protobuf]
   ------------------------ --------------- 3/5 [protobuf]
   ------------------------ --------------- 3/5 [protobuf]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   ---------------------------------------- 5/5 [kaggle]

Successfully installed kaggle-1.7.4.5 protobuf-6.31.1 python-slugify-8.0.4 text-unidecode-1.3 tqdm-4.67.1

In [5]:
import kaggle

In [22]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv to C:\Users\This PC

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 92.1MB/s]

In [39]:
import os

folder = r"C:\Users\This PC\SQL + python Proj"
print(os.listdir(folder))

['archive', 'archive.zip', 'orders.csv', 'SQL+PythonProj.ipynb']

In [40]:
import pandas as pd
df = pd.read_csv(r"C:\Users\This PC\SQL + python Proj\orders.csv")

In [41]:
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [47]:
#df.columns= df.columns.str.lower()

df.columns= df.columns.str.replace(' ', '_')

In [48]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [50]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [51]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [89]:
df['discount'] = df['list_price']*df['discount_percent']*0.01

In [90]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0

In [91]:
df['sale_price'] = df['list_price'] - df['discount']
df['profit'] = df['sale_price'] - df['cost_price']

In [92]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [93]:
df['order_date'] = pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [94]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [96]:
df.drop(columns=['list_price','cost_price','discount_percent'], inplace= True)

In [97]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [65]:
!pip install SQLAlchemy

Collecting SQLAlchemy
  Downloading sqlalchemy-2.0.41-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Downloading greenlet-3.2.3-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\this pc\appdata\local\programs\python\python313\lib\site-packages (from SQLAlchemy) (4.14.0)
Downloading sqlalchemy-2.0.41-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 3.0 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 2.8 MB/s eta 0:00:00
Downloading greenlet-3.2.3-cp313-cp313-win_amd64.whl (297 kB)
Installing collected packages: greenlet, SQLAlchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   ---------------------------------------- 2/2 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.41 greenlet-3.2.3

In [67]:
import sqlalchemy as sal
engine = sal.create_engine('mssql:DESKTOP-4BJAINC/Netflix?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn = engine.connect()

ArgumentError: Could not parse SQLAlchemy URL from given URL string

In [72]:
import sqlalchemy as sal
engine = sal.create_engine('mssql://DESKTOP-4BJAINC/Netflix?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes')
conn = engine.connect()

ModuleNotFoundError: No module named 'pyodbc'

In [73]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.2.0-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.2.0-cp313-cp313-win_amd64.whl (69 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.2.0

In [74]:
import sqlalchemy as sal

engine = sal.create_engine(
    'mssql+pyodbc://@DESKTOP-4BJAINC/Netflix?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes'
)
conn = engine.connect()

In [75]:
conn

In [76]:
df.to_sql('df_orders', con=conn, index=False, if_exists = 'replace')

38

In [77]:
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])

In [98]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [87]:
#df.columns= df.columns.str.lower()

df.columns= df.columns.str.replace(' ', '_')

In [99]:
df.to_sql('df_orders', con=conn, index=False, if_exists = 'append')

38

In [100]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8